#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/dc60a31e79380895a7375b498c4e7c04
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $public_ipv4
    metadata: region=europe-west1,az=europe-west1-a
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker-images.service
      command: start
      content: |
        [Unit]
        Description=Pulls Docker images
        Requires=docker.service
        After=docker.service
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/docker pull redis:latest
        ExecStart=/usr/bin/docker pull mysql:latest
        ExecStart=/usr/bin/docker pull postgres:latest
        ExecStart=/usr/bin/docker pull mongo:latest
        ExecStart=/usr/bin/docker pull tutum/rabbitmq:latest
        ExecStart=/usr/bin/docker pull ubuntu:latest
        ExecStart=/usr/bin/docker pull ubuntu-upstart:latest
        ExecStart=/usr/bin/docker pull phusion/baseimage:latest
    # https://coreos.com/docs/cluster-management/setup/mounting-storage/
    # http://www.freedesktop.org/software/systemd/man/systemd.swap.html
    - name: mkswap-sdb.service
      command: start
      content: |
        [Unit]
        Description=Formats the swap drive
        Requires=dev-sdb.device
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/mkswap -f /dev/sdb
    - name: dev-sdb.swap
      command: start
      content: |
        [Install]
        WantedBy=dev-sdb.device
        [Unit]
        Description=Enables the swap drive
        Requires=mkswap-sdb.service
        After=mkswap-sdb.service
        [Swap]
        What=/dev/sdb
